---
title: "[Pyod] df0.03~0.01"
author: "김보람 "
date: "02/22/2024"
---

1. 2/22

2. 4/5


ref: <https://pyod.readthedocs.io/en/latest/pyod.models.html#all-models>

# 1. Imports

In [1]:
import pandas as pd
import numpy as np
import sklearn
import pickle 
import time 
import datetime

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
%run ../functions_pyod2.py

In [4]:
with open('../fraudTrain.pkl', 'rb') as file:
    fraudTrain = pickle.load(file)

# 2.

In [5]:
pyod(*pyod_preprocess4(fraudTrain, 0.03))

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params
0,ECOD,0.351176,0.962917,0.389481,0.383858,0.386649,0.682481,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None
1,GMM,0.223286,0.969950,0.506605,0.503281,0.504937,0.743944,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None
2,HBOS,1.267061,0.969211,0.000000,0.000000,0.000000,0.499825,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None
3,IForest,3.864446,0.970130,0.509660,0.501969,0.505785,0.743401,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None
4,INNE,4.864259,0.969950,0.506605,0.503281,0.504937,0.743944,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None
5,KNN,0.275712,0.969790,0.503891,0.509843,0.506849,0.747039,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None
6,LODA,0.615552,0.969211,0.000000,0.000000,0.000000,0.499825,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None
7,LOF,0.533938,0.935944,0.035359,0.041995,0.038392,0.503007,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None
8,MCD,0.068930,0.969950,0.506605,0.503281,0.504937,0.743944,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None
9,PCA,0.045984,0.968631,0.484687,0.477690,0.481163,0.730870,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None
10,ROD,11.170515,0.940160,0.000000,0.000000,0.000000,0.484843,False,pyod,0.03,150150,[amt],0.02985,50050,0.03045,None

In [6]:
pyod(*pyod_preprocess4(fraudTrain, 0.02))

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params
0,ECOD,0.052304,0.972681,0.332468,0.333550,0.333008,0.659786,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None
1,GMM,0.197402,0.978328,0.471069,0.487948,0.479360,0.738256,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None
2,HBOS,0.011245,0.979181,0.000000,0.000000,0.000000,0.499810,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None
3,IForest,5.727317,0.978528,0.475493,0.486645,0.481005,0.737720,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None
4,INNE,7.201674,0.973693,0.353529,0.345928,0.349687,0.666362,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None
5,KNN,0.436417,0.976450,0.427685,0.448860,0.438017,0.718161,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None
6,LODA,1.262170,0.979181,0.000000,0.000000,0.000000,0.499810,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None
7,LOF,0.711294,0.961172,0.003597,0.003257,0.003419,0.492212,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None
8,MCD,0.063037,0.978328,0.471069,0.487948,0.479360,0.738256,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None
9,PCA,0.051780,0.978488,0.474194,0.478827,0.476499,0.733872,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None
10,ROD,12.891927,0.963077,0.000000,0.000000,0.000000,0.491590,False,pyod,0.02,225225,[amt],0.019851,75075,0.020446,None

In [7]:
pyod(*pyod_preprocess4(fraudTrain, 0.01))

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params
0,ECOD,0.107034,0.984862,0.230047,0.233651,0.231835,0.612965,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None
1,GMM,0.310075,0.989477,0.462315,0.467984,0.465132,0.731305,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None
2,HBOS,0.021316,0.989910,0.000000,0.000000,0.000000,0.499842,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None
3,IForest,12.080396,0.989477,0.462315,0.467984,0.465132,0.731305,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None
4,INNE,15.223820,0.989764,0.475958,0.465259,0.470548,0.730101,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None
5,KNN,1.047838,0.987852,0.380215,0.384877,0.382532,0.689341,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None
6,LODA,2.308631,0.989910,0.000000,0.000000,0.000000,0.499842,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None
7,LOF,1.631075,0.981945,0.000803,0.000681,0.000737,0.496157,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None
8,MCD,0.118274,0.989477,0.462315,0.467984,0.465132,0.731305,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None
9,PCA,0.051475,0.989477,0.462315,0.467984,0.465132,0.731305,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None
10,ROD,14.533673,0.977882,0.000539,0.000681,0.000602,0.494106,False,pyod,0.01,450450,[amt],0.010074,150150,0.009777,None

In [8]:
pyod(*pyod_preprocess4(fraudTrain, 0.00573))

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params
0,ECOD,0.188112,0.989807,0.118908,0.122163,0.120514,0.558479,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None
1,GMM,0.533127,0.992757,0.368421,0.373832,0.371107,0.685074,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None
2,HBOS,0.032253,0.993974,0.000000,0.000000,0.000000,0.499845,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None
3,IForest,20.315008,0.992772,0.369393,0.373832,0.371599,0.685081,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None
4,INNE,29.825281,0.992818,0.365922,0.349800,0.357679,0.673157,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None
5,KNN,4.423362,0.992024,0.301874,0.301068,0.301471,0.648532,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None
6,LODA,2.266625,0.993974,0.000000,0.000000,0.000000,0.499845,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None
7,LOF,7.412388,0.988590,0.000000,0.000000,0.000000,0.497137,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None
8,MCD,0.181860,0.992757,0.368421,0.373832,0.371107,0.685074,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None
9,PCA,0.062905,0.992757,0.368421,0.373832,0.371107,0.685074,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None
10,ROD,20.493737,0.986357,0.000000,0.000000,0.000000,0.496014,False,pyod,0.00573,786126,[amt],0.005734,262042,0.005717,None

In [9]:
pyod(*pyod_preprocess4(fraudTrain, 0.006))

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params
0,ECOD,0.195777,0.989443,0.112075,0.113590,0.112827,0.554120,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None
1,GMM,0.305787,0.992707,0.383423,0.384719,0.384070,0.690521,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None
2,HBOS,0.040378,0.993834,0.000000,0.000000,0.000000,0.499871,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None
3,IForest,24.509133,0.992699,0.382591,0.383367,0.382979,0.689845,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None
4,INNE,28.267958,0.992719,0.382935,0.379310,0.381114,0.687838,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None
5,KNN,1.973125,0.991792,0.304022,0.301555,0.302783,0.648725,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None
6,LODA,3.668576,0.993834,0.000000,0.000000,0.000000,0.499871,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None
7,LOF,2.910123,0.987996,0.002609,0.002705,0.002656,0.498279,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None
8,MCD,0.151791,0.992707,0.383423,0.384719,0.384070,0.690521,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None
9,PCA,0.055543,0.992707,0.383423,0.384719,0.384070,0.690521,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None
10,ROD,20.826998,0.992595,0.000000,0.000000,0.000000,0.499248,False,pyod,0.006,750750,[amt],0.00603,250250,0.00591,None

In [10]:
pyod(*pyod_preprocess4(fraudTrain, 0.007))

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params
0,ECOD,0.153141,0.988564,0.168407,0.179541,0.173796,0.586781,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None
1,GMM,0.165119,0.992420,0.436105,0.448852,0.442387,0.722469,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None
2,HBOS,0.029190,0.992956,0.000000,0.000000,0.000000,0.499826,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None
3,IForest,19.103554,0.992438,0.437032,0.446764,0.441844,0.721441,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None
4,INNE,23.265383,0.991501,0.367263,0.371608,0.369422,0.683645,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None
5,KNN,1.646159,0.991012,0.333559,0.342380,0.337912,0.668883,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None
6,LODA,3.402226,0.992956,0.000000,0.000000,0.000000,0.499826,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None
7,LOF,2.516944,0.986872,0.000724,0.000696,0.000710,0.497109,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None
8,MCD,0.140492,0.992420,0.436105,0.448852,0.442387,0.722469,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None
9,PCA,0.074887,0.992420,0.436105,0.448852,0.442387,0.722469,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None
10,ROD,16.611028,0.988434,0.000000,0.000000,0.000000,0.497550,False,pyod,0.007,643500,[amt],0.0071,214500,0.006699,None

In [11]:
pyod(*pyod_preprocess4(fraudTrain, 0.008))

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params
0,ECOD,0.123736,0.987005,0.206966,0.197570,0.202159,0.595604,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None
1,GMM,0.330886,0.990910,0.454835,0.457161,0.455995,0.726278,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None
2,HBOS,0.023745,0.991310,0.000000,0.000000,0.000000,0.499820,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None
3,IForest,16.411341,0.990942,0.456298,0.453964,0.455128,0.724709,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None
4,INNE,19.425026,0.990543,0.430820,0.420077,0.425380,0.707707,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None
5,KNN,1.344512,0.989515,0.367801,0.359335,0.363519,0.677072,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None
6,LODA,2.643924,0.991310,0.000000,0.000000,0.000000,0.499820,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None
7,LOF,2.312454,0.984080,0.000000,0.000000,0.000000,0.496175,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None
8,MCD,0.135582,0.990910,0.454835,0.457161,0.455995,0.726278,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None
9,PCA,0.045846,0.990910,0.454835,0.457161,0.455995,0.726278,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None
10,ROD,19.313411,0.991608,0.000000,0.000000,0.000000,0.499970,False,pyod,0.008,563062,[amt],0.007889,187688,0.008333,None

In [12]:
pyod(*pyod_preprocess4(fraudTrain, 0.009))

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params
0,ECOD,0.133286,0.985656,0.213953,0.210183,0.212051,0.601513,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None
1,GMM,0.271031,0.990506,0.482759,0.475196,0.478947,0.735239,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None
2,HBOS,0.025840,0.990440,0.000000,0.000000,0.000000,0.499809,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None
3,IForest,13.328631,0.990589,0.487231,0.473238,0.480132,0.734311,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None
4,INNE,16.642746,0.985878,0.139860,0.104439,0.119581,0.549243,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None
5,KNN,1.165346,0.989025,0.399732,0.389034,0.394310,0.691810,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None
6,LODA,2.162688,0.990440,0.000000,0.000000,0.000000,0.499809,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None
7,LOF,1.929125,0.982084,0.000685,0.000653,0.000669,0.495916,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None
8,MCD,0.106577,0.990506,0.482759,0.475196,0.478947,0.735239,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None
9,PCA,0.049383,0.990506,0.482759,0.475196,0.478947,0.735239,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None
10,ROD,18.978061,0.975215,0.000384,0.000653,0.000483,0.492450,False,pyod,0.009,500499,[amt],0.008939,166834,0.009183,None