---
title: "[Proposed] df50"
author: "김보람"
date: "02/14/2024"
---

# imports

In [1]:
import pandas as pd
import numpy as np
import sklearn
import pickle 
import time 
import datetime
import warnings
warnings.filterwarnings('ignore')

In [2]:
%run ../function_proposed_gcn.py

In [3]:
with open('../fraudTrain.pkl', 'rb') as file:
    fraudTrain = pickle.load(file)

In [4]:
df50 = throw(fraudTrain,0.5)

In [8]:
df_results = try_1(df50, 0.5, 0.5, 10973.519989002007, 0.501)
df_results = try_1(df50, 0.5, 0.5, 15000, 0.5, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 15000, 0.6, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 15000, 0.7, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 15000, 0.8, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 15000, 0.9, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 15000, 0.4, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 15000, 0.3, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 15000, 0.2, prev_results=df_results)
ymdhms = datetime.datetime.fromtimestamp(time.time()).strftime('%Y%m%d-%H%M%S') 
df_results.to_csv(f'../results/{ymdhms}-proposed.csv',index=False)

df_results

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params,theta,gamma
0,GCN,None,0.891757,0.959609,0.817879,0.883094,0.925402,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,10973.519989,0.501
1,GCN,None,0.903969,0.959570,0.843420,0.897754,0.936666,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,15000.000000,0.500
2,GCN,None,0.890647,0.960105,0.815103,0.881682,0.925188,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,15000.000000,0.600
3,GCN,None,0.884541,0.960745,0.801777,0.874092,0.915326,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,15000.000000,0.700
4,GCN,None,0.880377,0.950066,0.802887,0.870298,0.902739,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,15000.000000,0.800
5,GCN,None,0.872884,0.959617,0.778456,0.859595,0.876013,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,15000.000000,0.900
6,GCN,None,0.908132,0.956522,0.855081,0.902961,0.942754,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,15000.000000,0.400
7,GCN,None,0.913961,0.952641,0.871183,0.910093,0.947405,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,15000.000000,0.300
8,GCN,None,0.912295,0.962617,0.857857,0.907223,0.952030,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,15000.000000,0.200

In [9]:
df_results = try_1(df50, 0.5, 0.5, 10000, 0.2)
df_results = try_1(df50, 0.5, 0.5, 10000, 0.2, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 10000, 0.18, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 10000, 0.16, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 10000, 0.14, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 10000, 0.12, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 10000, 0.10, prev_results=df_results)
df_results.to_csv(f'../results/{ymdhms}-proposed.csv',index=False)

df_results

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params,theta,gamma
0,GCN,None,0.909797,0.961827,0.853415,0.904384,0.946367,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,10000,0.20
1,GCN,None,0.910075,0.961274,0.854525,0.904762,0.946356,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,10000,0.20
2,GCN,None,0.910352,0.961298,0.855081,0.905084,0.946452,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,10000,0.18
3,GCN,None,0.913961,0.956522,0.867296,0.909726,0.947426,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,10000,0.16
4,GCN,None,0.912295,0.962041,0.858412,0.907277,0.948787,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,10000,0.14
5,GCN,None,0.915903,0.957265,0.870627,0.911893,0.950264,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,10000,0.12
6,GCN,None,0.917291,0.957395,0.873404,0.913473,0.951514,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,10000,0.10

In [10]:
df_results = try_1(df50, 0.5, 0.5, 98000, 0.1)
df_results = try_1(df50, 0.5, 0.5, 96000, 0.1, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 94000, 0.1, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 92000, 0.1, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 90000, 0.1, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 88000, 0.1, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 86000, 0.1, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 84000, 0.1, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 82000, 0.1, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 80000, 0.1, prev_results=df_results)
df_results.to_csv(f'../results/{ymdhms}-proposed.csv',index=False)

df_results

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params,theta,gamma
0,GCN,None,0.964752,0.973416,0.955580,0.964416,0.987621,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,98000,0.1
1,GCN,None,0.967527,0.965193,0.970017,0.967599,0.987662,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,96000,0.1
2,GCN,None,0.967250,0.964660,0.970017,0.967331,0.987736,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,94000,0.1
3,GCN,None,0.967250,0.964660,0.970017,0.967331,0.987737,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,92000,0.1
4,GCN,None,0.968637,0.968368,0.968906,0.968637,0.987742,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,90000,0.1
5,GCN,None,0.968360,0.967831,0.968906,0.968368,0.987859,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,88000,0.1
6,GCN,None,0.966972,0.964128,0.970017,0.967063,0.987888,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,86000,0.1
7,GCN,None,0.968082,0.970950,0.965019,0.967975,0.987927,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,84000,0.1
8,GCN,None,0.967805,0.965727,0.970017,0.967867,0.987995,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,82000,0.1
9,GCN,None,0.966972,0.964128,0.970017,0.967063,0.988069,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,80000,0.1

In [11]:
df_results = try_1(df50, 0.5, 0.5, 88000, 0.2)
df_results = try_1(df50, 0.5, 0.5, 96000, 0.3, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 94000, 0.4, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 92000, 0.5, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 90000, 0.6, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 88000, 0.7, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 86000, 0.8, prev_results=df_results)
df_results = try_1(df50, 0.5, 0.5, 84000, 0.9, prev_results=df_results)
df_results.to_csv(f'../results/{ymdhms}-proposed.csv',index=False)

df_results

,model,time,acc,pre,rec,f1,auc,graph_based,method,throw_rate,train_size,train_cols,train_frate,test_size,test_frate,hyper_params,theta,gamma
0,GCN,None,0.967250,0.972487,0.961688,0.967058,0.987065,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,88000,0.2
1,GCN,None,0.965307,0.965039,0.965575,0.965307,0.986926,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,96000,0.3
2,GCN,None,0.963364,0.963354,0.963354,0.963354,0.984985,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,94000,0.4
3,GCN,None,0.937552,0.954965,0.918379,0.936315,0.968513,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,92000,0.5
4,GCN,None,0.928948,0.950437,0.905053,0.927190,0.962901,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,90000,0.6
5,GCN,None,0.913405,0.963863,0.858967,0.908397,0.957015,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,88000,0.7
6,GCN,None,0.915071,0.953855,0.872293,0.911253,0.948241,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,86000,0.8
7,GCN,None,0.895087,0.961713,0.822876,0.886894,0.931524,True,Proposed,0.5,8409,amt,0.500059,3603,0.5,None,84000,0.9